language: c

sudo: false

_packages:
  - &i386-packages
    apt:
      packages:
      - gcc-multilib
_environments:
  - &i386-env
    - TOOLCHAIN=gcc-i686
  - &i386-darwin-env
    - TOOLCHAIN=gcc-darwin-i686

matrix:
  include:
  # Linux
    # x86_64
    - env: CONFIGURATION=Debug
      compiler: gcc
    - env: CONFIGURATION=Release
      compiler: gcc
    - env: CONFIGURATION=RelWithDebInfo
      compiler: gcc
    # i386
    - env: [CONFIGURATION=Debug, *i386-env]
      addons: *i386-packages
      compiler: gcc
    - env: [CONFIGURATION=Release, *i386-env]
      addons: *i386-packages
      compiler: gcc
    - env: [CONFIGURATION=RelWithDebInfo, *i386-env]
      addons: *i386-packages
      compiler: gcc
  # OS X
    # x86_64
    - env: CONFIGURATION=Debug
      os: osx
      compiler: clang
    - env: CONFIGURATION=Release
      os: osx
      compiler: clang
    - env: CONFIGURATION=RelWithDebInfo
      os: osx
      compiler: clang
    - env: [CONFIGURATION=Debug, *i386-darwin-env]
      os: osx
      compiler: clang
    - env: [CONFIGURATION=Release, *i386-darwin-env]
      os: osx
      compiler: clang
    - env: [CONFIGURATION=RelWithDebInfo, *i386-darwin-env]
      os: osx
      compiler: clang

before_install:
  - if [ -z "${TARGET}" ]; then export TARGET=${ARCH}; fi
  - if [ -n "${SUDO_PKG}" ]; then sudo apt-get install -qq ${SUDO_PKG}; fi

script:
  - mkdir -p build && cd $_
  - |
      if [ -n "${TOOLCHAIN}" ]; then
        TC_FILE="../.cmake/Toolchains/Toolchain-${TOOLCHAIN}.cmake"
        if [ -n "${ARCH}" ]; then
            export CMAKE_OPTS="${CMAKE_OPTS} -DARCH=${ARCH}"
            export CMAKE_OPTS="${CMAKE_OPTS} -DTARGET=${TARGET}"
        fi
        export CMAKE_OPTS="${CMAKE_OPTS} -DCMAKE_TOOLCHAIN_FILE=${TC_FILE}"
      fi
  - >
      cmake
      -Wno-dev
      -DCMAKE_BUILD_TYPE=${CONFIGURATION}
      -DCMAKE_INSTALL_PREFIX=tizzy-${TRAVIS_TAG}
      ${CMAKE_OPTS}
      ..
  - TERM=dumb cmake --build . -- -j4
  - |
      if [ "${TESTS:-ON}" = "ON" ]; then
        ctest --output-on-failure
      fi
